name="Wild Duck Mail"

title="wildduck-www"

[service]
    # email domain for new users
    domain="localhost"
    # default quotas for new users
    quota=1024
    recipients=2000
    forwards=2000
    allowJoin=true

[api]
    url="http://127.0.0.1:8080"
    accessToken=""

[dbs]
    # mongodb connection string for the main database
    mongo="mongodb://127.0.0.1:27017/archive"

    # redis connection string for Express sessions
    redis="redis://127.0.0.1:6379/5"

[www]
    host=false
    port=3000
    proxy=false
    postsize="5MB"
    log="dev"
    secret="a cat"
    baseurl="http://localhost" # link used in emails etc
    secure=false
    listSize=20

[totp]
    # Issuer name for TOTP, defaults to config.name
    issuer=false
    # changing secret invalidates all existing 2fa sessions
    secret="a secret cat"

[u2f]
    # set to false if not using HTTPS
    enabled=true

[log]
    level="silly"
    mail=true

[setup]
    # these values are shown in the configuration help page
    [setup.imap]
        hostname="localhost"
        secure=true
        port=9993
    [setup.pop3]
        hostname="localhost"
        secure=true
        port=9995
    [setup.smtp]
        hostname="localhost"
        secure=false
        port=2587
